; PlatformIO Project Configuration File
; Modo: monitoreo local con OV2640 + SHT3X + OLED

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; PSRAM — habilitar solo si la placa lo tiene detectado correctamente
build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
	adafruit/Adafruit SSD1306@^2.5.12
	espressif/esp32-camera@^2.0.0
	bblanchon/ArduinoJson@^6.21.4

; Solo compilar los archivos del firmware de monitoreo
src_filter = +<main.cpp> +<libcam.cpp> +<libdisplay.cpp> +<libweb.cpp>

monitor_speed = 115200
upload_speed  = 460800
upload_port   = COM3    ; cambia por tu COM real
